<a href="https://colab.research.google.com/github/Clara-co/Clara-co/blob/main/Health_informatics_huggingface_model_search.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from huggingface_hub import HfApi
import pandas as pd

In [4]:
api = HfApi()

In [5]:
models = api.list_models(search='health')

In [6]:
from huggingface_hub import HfApi
import pandas as pd

def collect_models_from_search(api, query_str):
  df = pd.DataFrame(columns=['id', 'tags', 'downloads'])
  models = api.list_models(search=query_str)
  for model in models:
    new_row = {'id': model.id,
               'tags': model.tags,
               'downloads': model.downloads
               }
    new_row_df = pd.DataFrame([new_row])
    df = pd.concat([df, new_row_df], ignore_index=True)
  return df

In [7]:
health_df = collect_models_from_search(api, "health")
medical_df = collect_models_from_search(api, "medical")
clinical_df = collect_models_from_search(api, "clinical")
medicine_df = collect_models_from_search(api, "medicine")
disease_df = collect_models_from_search(api, "disease")
treatment_df = collect_models_from_search(api, "treatment")
diagnosis_df = collect_models_from_search(api, "diagnosis")
healthcare_df = collect_models_from_search(api, "healthcare")
hospital_df = collect_models_from_search(api, "hospital")
patient_df = collect_models_from_search(api, "patient")

In [8]:
print ('health_df', len(health_df))
print ('medical_df', len(medical_df))
print ('clinical_df', len(clinical_df))
print ('medicine_df', len(medicine_df))
print ('disease_df', len(disease_df))
print ('treatment_df', len(treatment_df))
print ('diagnosis_df', len(diagnosis_df))
print ('healthcare_df', len(healthcare_df))
print ('hospital_df', len(hospital_df))
print ('patient_df', len(patient_df))

health_df 4022
medical_df 5904
clinical_df 1242
medicine_df 342
disease_df 1386
treatment_df 47
diagnosis_df 192
healthcare_df 407
hospital_df 93
patient_df 171

In [9]:
display(health_df)

,id,tags,downloads
0,m42-health/Llama3-Med42-70B,"[transformers, safetensors, llama, text-genera...",4964
1,m42-health/Llama3-Med42-8B,"[transformers, safetensors, llama, text-genera...",4234
2,FarhanAli/RoBERT_healthFact,[region:us],0
3,FarhanAli/health_fact_data_models,[region:us],0
4,explosion/en_healthsea,"[spacy, token-classification, text-classificat...",43
...,...,...,...
4017,help2opensource/Qwen3-8B_mental_health_cbt,"[peft, safetensors, base_model:adapter:Qwen/Qw...",13
4018,MrOceanMan/rl_course_vizdoom_health_gathering_...,"[sample-factory, tensorboard, deep-reinforceme...",0
4019,yashaswiniIv/soil-health-recommender,"[license:apache-2.0, region:us]",0
4020,Aubins/RL_Course_vizdoom_health_gathering_supreme,"[sample-factory, tensorboard, deep-reinforceme...",0
4021,help2opensource/Qwen3-4B-Instruct-2507_mental_...,"[peft, safetensors, base_model:adapter:Qwen/Qw...",45

In [ ]:
display(medical_df)

,id,tags,downloads
0,Intelligent-Internet/II-Medical-8B-1706,"[transformers, safetensors, qwen3, text-genera...",7208
1,medicalai/ClinicalBERT,"[transformers, pytorch, distilbert, fill-mask,...",472506
2,HUMADEX/german_medical_ner,"[pytorch, safetensors, bert, NER, medical, sym...",89
3,emredeveloper/DeepSeek-R1-Medical-COT,"[transformers, pytorch, safetensors, llama, te...",13
4,deca-ai/2-pro-medical,"[transformers, safetensors, llama, text-genera...",23
...,...,...,...
5521,penelitianpsmatematika/grpo-medical-text-gener...,"[transformers, safetensors, t5, text2text-gene...",6
5522,herozs/deepseek_medical_finetuned,[region:us],0
5523,lindafei001/my-llama3-instruct-medical-sudo-5e...,[region:us],0
5524,hassan912/whisper-medical-ct2,[region:us],0
5525,MohamedAhmedAE/Llama-3.2-1B-Instruct-Medical-F...,"[transformers, safetensors, generated_from_tra...",0

In [ ]:
display(clinical_df)

,id,tags,downloads
0,medicalai/ClinicalBERT,"[transformers, pytorch, distilbert, fill-mask,...",472506
1,emilyalsentzer/Bio_ClinicalBERT,"[transformers, pytorch, tf, jax, bert, fill-ma...",2723588
2,clinical-assistance/whisper-large-v3-clinical-...,"[transformers, safetensors, whisper, automatic...",7
3,rohitanurag/ClinicalGPT-Pubmed-Instruct-V1.0,"[peft, safetensors, mistral, medical, lifescie...",0
4,Raymond-dev-546730/ClinicalThought-AI-8B,"[safetensors, gguf, medical-ai, clinical-reaso...",333
...,...,...,...
1215,Ghostraptor/Trained_clinical_Bert,"[license:mit, region:us]",7
1216,Akashhhhwqx/tinyllama-clinical-summarizer,"[transformers, safetensors, arxiv:1910.09700, ...",0
1217,cookienter/lifechart-clinicalbert-classifier-h...,"[transformers, safetensors, bert, text-classif...",5
1218,mradermacher/llama-3.1-8b-clinical-V2.0-GGUF,"[transformers, gguf, en, base_model:CodCodingC...",0
1219,mradermacher/Clinical-AI-llama-GGUF,"[transformers, gguf, unsloth, trl, sft, en, ba...",0

In [ ]:
display(medicine_df)

,id,tags,downloads
0,9pinus/macbert-base-chinese-medicine-recognition,"[transformers, pytorch, bert, token-classifica...",53
1,Zach88/nuclear_medicine_DABERT,"[transformers, pytorch, bert, fill-mask, autot...",1
2,Zach88/nuclear_medicine_DAbioClincialBERT,"[transformers, pytorch, bert, fill-mask, autot...",14
3,Zach88/nuclear_medicine_DARoBERTa,"[transformers, pytorch, roberta, fill-mask, au...",2
4,jarvisx17/medicine-ner,"[transformers, pytorch, tensorboard, distilber...",1
...,...,...,...
323,AmanPriyanshu/gpt-oss-20.3b-specialized-health...,"[safetensors, gpt_oss, mixture-of-experts, moe...",10
324,AmanPriyanshu/gpt-oss-20.9b-specialized-health...,"[safetensors, gpt_oss, mixture-of-experts, moe...",11
325,Team-Promptia/Qwen2.5-7B-RLT-medicine_biology-...,"[safetensors, region:us]",39
326,yangguohao/medicine-classification,[region:us],0
327,Team-Promptia/RLT-student-Qwen3-32B-medicine_b...,"[safetensors, qwen3, qwen, medicine, biology, ...",24

In [ ]:
display(disease_df)

,id,tags,downloads
0,linkanjarad/mobilenet_v2_1.0_224-plant-disease...,"[transformers, pytorch, tensorboard, mobilenet...",2542
1,wambugu71/crop_leaf_diseases_vit,"[transformers, safetensors, vit, image-classif...",2678
2,YuchengShi/LLaVA-v1.5-7B-Plant-Leaf-Diseases-D...,"[transformers, safetensors, llava, image-to-te...",59
3,Aaditya456/Banana-Disease-Classification,"[keras, region:us]",49
4,alvaroalon2/biobert_diseases_ner,"[transformers, pytorch, bert, token-classifica...",5772
...,...,...,...
1338,sadanandkumar8789/plant-leaf-disease-model,[region:us],0
1339,bharath56858/hen-disease-detection,"[license:apache-2.0, region:us]",0
1340,Monishasp/leaf-disease-model,"[keras, license:mit, region:us]",39
1341,JadhavAdi123/apple_disease.h5,"[license:apache-2.0, region:us]",0
1342,bisoye/crop-disease-model,[region:us],0

In [ ]:
display(treatment_df)

,id,tags,downloads
0,jnferfer/treatment-disease-NER,"[transformers, pytorch, tensorboard, bert, tok...",6
1,Straiberry/Treatment_Recommendation,"[transformers, pytorch, distilbert, text-class...",3
2,pjc2178/llama-for-case-treatment-v0,[region:us],0
3,KeiHeityuu/Recognition_of_intention_in_medical...,[region:us],0
4,bgalitsky/t5_recommendation_treatment,"[transformers, pytorch, tensorboard, t5, text2...",2
5,lakshmi31/t5_recommendation_treatment,"[transformers, pytorch, tensorboard, t5, text2...",1
6,Yuktakulkarni04/t5_recommendation_treatment,"[transformers, pytorch, tensorboard, t5, text2...",0
7,emilykang/medquad-treatment_lora,"[peft, safetensors, trl, sft, generated_from_t...",0
8,emilykang/medquad-treatment,"[transformers, safetensors, llama, text-genera...",2
9,emilykang/Gemma_medquad-treatment_lora,"[peft, safetensors, trl, sft, generated_from_t...",0
10,emilykang/Gemma_medquad-treatment,"[transformers, safetensors, gemma, text-genera...",2
11,emilykang/Phi_medquad-treatment_lora,"[peft, safetensors, trl, sft, generated_from_t...",0
12,emilykang/Phi_medquad-treatment,"[transformers, safetensors, phi, text-generati...",2
13,etadevosyan/did_the_doctor_thank_the_patient_f...,"[transformers, safetensors, bert, text-classif...",2
14,nitzanb/hebnlp_test2_base30062024_diseases_dru...,"[transformers, safetensors, bert, token-classi...",0
15,Waleed-Ijaz/dental_treatment_model,"[license:unknown, region:us]",0
16,bryantky/Whisper-TreatmentPlanning,"[transformers, endpoints_compatible, region:us]",1
17,bryantky/Whisper-TreatmentPlanning-Fast,"[transformers, endpoints_compatible, region:us]",1
18,daleilei/medical_treatment,"[gguf, llama, license:apache-2.0, endpoints_co...",72
19,Yanjo/datamix-treatment-12l,"[transformers, safetensors, gpt2, text-generat...",1
20,montassar97/Water_Treatment,"[license:apache-2.0, region:us]",0
21,IvanPerkhun/did_the_doctor_thank_the_patient_f...,"[transformers, safetensors, bert, text-classif...",2
22,swe310/t5_recommendation_treatment,[region:us],0
23,Unmeshraj/skin-disease-treatment-plan,"[transformers, safetensors, bert, feature-extr...",2
24,Unmeshraj/skin-disease-treatment-promax,"[safetensors, bert, region:us]",2
25,316usman/Phi-3-mini-4k-instruct-3-epochs-medqu...,"[transformers, safetensors, text-generation-in...",0
26,thanawatpi/appherb-treatment-pred-beta,"[peft, safetensors, question-answering, th, ar...",1
27,RichardErkhov/Yanjo_-_datamix-treatment-12l-exl2,[region:us],0
28,cagriefe/biogpt-medical-treatment-base,"[license:apache-2.0, region:us]",0
29,RichardErkhov/Yanjo_-_datamix-treatment-12l-gguf,[region:us],0
30,RichardErkhov/Yanjo_-_datamix-treatment-12l-4bits,"[safetensors, gpt2, 4-bit, bitsandbytes, regio...",4
31,RichardErkhov/Yanjo_-_datamix-treatment-12l-8bits,"[safetensors, gpt2, 8-bit, bitsandbytes, regio...",4
32,submarat/gpt2-medium-fast-schedule-special-tre...,"[safetensors, gpt2, region:us]",4
33,mradermacher/datamix-treatment-12l-GGUF,"[transformers, gguf, generated_from_trainer, e...",13
34,mradermacher/Phi_medquad-treatment-GGUF,"[transformers, gguf, en, base_model:emilykang/...",1
35,mradermacher/Phi_medquad-treatment-i1-GGUF,"[transformers, gguf, en, base_model:emilykang/...",3
36,mradermacher/datamix-treatment-12l-i1-GGUF,"[transformers, gguf, generated_from_trainer, e...",51
37,jw3490/oncological_treatment_bert,[region:us],0
38,jw3490/oncological-treatment,"[safetensors, bert, text-classification, regio...",5
39,suayptalha/Qwen3-0.6B-Treatment,"[transformers, safetensors, qwen3, text-genera...",6
40,mradermacher/Qwen3-0.6B-Treatment-GGUF,"[transformers, gguf, unsloth, trl, sft, en, da...",127
41,mradermacher/Qwen3-0.6B-Treatment-i1-GGUF,"[transformers, gguf, unsloth, trl, sft, en, da...",144
42,jherronr/clinicalbert-treatment-classifier,"[safetensors, bert, region:us]",9
43,Lekhansh/bioclinical-treatment-detector,"[safetensors, modernbert, token-classification...",86

In [ ]:
display(diagnosis_df)

,id,tags,downloads
0,alpha-ai/Medical-Diagnosis-COT-Gemma3-270M,"[transformers, safetensors, gguf, gemma3_text,...",1254
1,DATEXIS/CORe-clinical-diagnosis-prediction,"[transformers, pytorch, bert, text-classificat...",1209
2,DongHyoungLee/bluebert-sitesentence-diagnosis-...,"[transformers, pytorch, bert, text-classificat...",17
3,merve/breast_cancernb8gjv4n-diagnosis-classifi...,"[sklearn, tabular-classification, baseline-tra...",0
4,DunnBC22/vit-base-patch16-224-in21k_GI_diagnosis,"[transformers, pytorch, tensorboard, vit, imag...",2
...,...,...,...
183,XuShihao6715/qwen3-8B_auxiliary_diagnosis_lora...,"[transformers, safetensors, qwen3, text-genera...",18
184,XuShihao6715/qwen3-8B_auxiliary_diagnosis_lora...,"[transformers, safetensors, qwen3, text-genera...",8
185,XuShihao6715/qwen3-8B_auxiliary_diagnosis_lora...,"[transformers, safetensors, qwen3, text-genera...",2
186,XuShihao6715/qwen3-8B-lora-sft-ds-r1_v2_auxili...,"[transformers, safetensors, qwen3, text-genera...",8
187,XuShihao6715/qwen3-8B-lora-sft-horizon-alpha-v...,"[transformers, safetensors, qwen3, text-genera...",6

In [ ]:
display(healthcare_df)

,id,tags,downloads
0,debadtman26/local-healthcare-chatbot,"[mlx, safetensors, mistral, text-generation, c...",27
1,pucpr/clinicalnerpt-healthcare,"[transformers, pytorch, bert, token-classifica...",596
2,NFflow/healthcare_27.03.2021-27.03.2022_reddit...,"[sentence-transformers, pytorch, distilbert, f...",3
3,Capstone/autotrain-healthcare_summarization_ut...,"[transformers, pytorch, autotrain, summarizati...",0
4,CreatorPhan/Healthcare-QnA,"[transformers, pytorch, t5, text2text-generati...",4
...,...,...,...
384,kkh27/healthcareLLM_v4_Tri-7B,"[safetensors, llama, region:us]",17
385,Jmorgo123/healthcare-assistant-ai,"[license:apache-2.0, region:us]",0
386,emrsvnc01/healthcare_v1,"[gguf, llama, license:mit, endpoints_compatibl...",42
387,swnometal666/finnish-healthcare-terminology-v3,"[safetensors, healthcare, medical, finnish, lo...",2
388,swnometal666/finnish-healthcare-terminology-v4,"[safetensors, healthcare, finnish, medical-ter...",0

In [ ]:
display(hospital_df)

,id,tags,downloads
0,bitext/Mistral-7B-Hospitality,"[pytorch, mistral, generated_from_trainer, tex...",60
1,mayoughi/where_am_I_hospital-balcony-hallway-a...,"[transformers, pytorch, tensorboard, vit, imag...",6
2,mayoughi/where_am_I_hospital-balcony-hallway-a...,"[transformers, pytorch, tensorboard, vit, imag...",6
3,hospitaltapes/langchain,[region:us],0
4,sillon/DialoGPT-small-HospitalBot,"[transformers, pytorch, gpt2, text-generation,...",13
...,...,...,...
86,dodoandchichi/51_hospital_classifier,"[safetensors, bert, license:mit, region:us]",10
87,dodoandchichi/52_hospital_classifier,"[safetensors, bert, license:mit, region:us]",8
88,shreyaspb/hospital-patient-forecaster,"[time-series, regression, xgboost, license:mit...",0
89,shreyaspb/hospital-patient-forecaster_v,"[time-series, regression, xgboost, license:mit...",0
90,vernscott22/my-hospitality-gpt2-lora,"[transformers, safetensors, arxiv:1910.09700, ...",0

In [ ]:
display(patient_df)

,id,tags,downloads
0,annedirkson/ADR_extraction_patient_forum,"[tf, region:us]",0
1,sap218/PatientINF,"[license:mit, region:us]",0
2,Jatin-WIAI/doctor_patient_clf_en,"[transformers, pytorch, bert, text-classificat...",16
3,humhealth/remote-patientmonitoring,"[license:bsl-1.0, region:us]",0
4,iotengtr/patient-condition,[region:us],0
...,...,...,...
154,shreyaspb/hospital-patient-forecaster,"[time-series, regression, xgboost, license:mit...",0
155,shreyaspb/hospital-patient-forecaster_v,"[time-series, regression, xgboost, license:mit...",0
156,UmeshAkade/gemma3-270m-med-wikidoc-patientinfo...,"[transformers, safetensors, text-generation-in...",0
157,patientxtr/wan22ti2v5bturbofp8e5m2,"[license:apache-2.0, region:us]",0
158,patientxtr/qwen-image-edit-fp8-e5m2,"[license:apache-2.0, region:us]",0

In [12]:
dfs = {

}

id_to_sources = {}

for name, df in dfs.items():
    for model_id in df['id'].unique():
        id_to_sources.setdefault(model_id, set()).add(name)

overlaps = {k: v for k, v in id_to_sources.items() if len(v) > 1}

overlap_df = pd.DataFrame([
    {"id": model_id, "count": len(sources), "dataframes": ", ".join(sorted(sources))}
    for model_id, sources in overlaps.items()
])

overlap_df = overlap_df.sort_values(by="count", ascending=False).reset_index(drop=True)

print("Top 20 models appearing in more than one keyword search:")
display(overlap_df.head(20))

overlap_df.to_csv("overlapping_models.csv", index=False)
overlap_df.to_excel("overlapping_models.xlsx", index=False)

print(f"\nSaved all {len(overlap_df)} overlaps to overlapping_models.csv and overlapping_models.xlsx")

Top 20 models appearing in more than one keyword search:

,id,count,dataframes
0,TheBlueObserver/Llama-3.2-3B-Instruct-Unsloth-...,4,"clinical, health, healthcare, medical"
1,falan42/llama_lora_8b_medical_HealthcareMagict...,3,"health, healthcare, medical"
2,falan42/llama_lora_8b_medical_HealthcareMagict...,3,"health, healthcare, medical"
3,udaysankarjalli/healthcare-disease-predictor-m...,3,"disease, health, healthcare"
4,falan42/phi_lora_3b_medical_HealthcareMagic_gguf,3,"health, healthcare, medical"
5,kms-healthcare/llama-lora-medical-model,3,"health, healthcare, medical"
6,IvanPerkhun/did_the_doctor_thank_the_patient_f...,3,"health, patient, treatment"
7,vishnupv123/Healthcare-IoT-Patient-Monitoring,3,"health, healthcare, patient"
8,KeiHeityuu/Recognition_of_intention_in_medical...,3,"diagnosis, medical, treatment"
9,pucpr/clinicalnerpt-healthcare,3,"clinical, health, healthcare"
10,etadevosyan/did_the_doctor_thank_the_patient_f...,3,"health, patient, treatment"
11,PChaturvedi87/healthcare-disease,3,"disease, health, healthcare"
12,omerdasc/flan-t5-healthcare-bot,2,"health, healthcare"
13,Pralod/lora-ntc-prototype-healthcare-chatbot-0-1,2,"health, healthcare"
14,Pralod/lora-qwen2.5-14B-ntc-prototype-healthca...,2,"health, healthcare"
15,sanjulamaduranga/BFL_Healthcare_skincancer,2,"health, healthcare"
16,person-swp/healthcare_SLM_1.0,2,"health, healthcare"
17,imbukwa/Tomato_Health_diseases,2,"disease, health"
18,drkumaranu165/healthcare-ner-colab,2,"health, healthcare"
19,sanjulamaduranga/BFL_Healthcare_covid_19,2,"health, healthcare"

Saved all 570 overlaps to overlapping_models.csv and overlapping_models.xlsx

In [13]:
dfs = {
    "health": health_df,
    "medical": medical_df,
    "clinical": clinical_df,
    "medicine": medicine_df,
    "disease": disease_df,
    "treatment": treatment_df,
    "diagnosis": diagnosis_df,
    "healthcare": healthcare_df,
    "hospital": hospital_df,
    "patient": patient_df
}

id_to_sources = {}

for name, df in dfs.items():
    for model_id in df['id'].unique():
        id_to_sources.setdefault(model_id, set()).add(name)

overlaps = {k: v for k, v in id_to_sources.items() if len(v) > 1}

overlap_df = pd.DataFrame([
    {"id": model_id, "count": len(sources), "dataframes": ", ".join(sorted(sources))}
    for model_id, sources in overlaps.items()
])

overlap_df = overlap_df.sort_values(by="count", ascending=False).reset_index(drop=True)

print("Top 20 models appearing in more than one keyword search:")
display(overlap_df.head(20))

overlap_df.to_csv("overlapping_models.csv", index=False)
overlap_df.to_excel("overlapping_models.xlsx", index=False)

print(f"\nSaved all {len(overlap_df)} overlaps to overlapping_models.csv and overlapping_models.xlsx")

Top 20 models appearing in more than one keyword search:

,id,count,dataframes
0,TheBlueObserver/Llama-3.2-3B-Instruct-Unsloth-...,4,"clinical, health, healthcare, medical"
1,falan42/llama_lora_8b_medical_HealthcareMagict...,3,"health, healthcare, medical"
2,falan42/llama_lora_8b_medical_HealthcareMagict...,3,"health, healthcare, medical"
3,udaysankarjalli/healthcare-disease-predictor-m...,3,"disease, health, healthcare"
4,falan42/phi_lora_3b_medical_HealthcareMagic_gguf,3,"health, healthcare, medical"
5,kms-healthcare/llama-lora-medical-model,3,"health, healthcare, medical"
6,IvanPerkhun/did_the_doctor_thank_the_patient_f...,3,"health, patient, treatment"
7,vishnupv123/Healthcare-IoT-Patient-Monitoring,3,"health, healthcare, patient"
8,KeiHeityuu/Recognition_of_intention_in_medical...,3,"diagnosis, medical, treatment"
9,pucpr/clinicalnerpt-healthcare,3,"clinical, health, healthcare"
10,etadevosyan/did_the_doctor_thank_the_patient_f...,3,"health, patient, treatment"
11,PChaturvedi87/healthcare-disease,3,"disease, health, healthcare"
12,omerdasc/flan-t5-healthcare-bot,2,"health, healthcare"
13,Pralod/lora-ntc-prototype-healthcare-chatbot-0-1,2,"health, healthcare"
14,Pralod/lora-qwen2.5-14B-ntc-prototype-healthca...,2,"health, healthcare"
15,sanjulamaduranga/BFL_Healthcare_skincancer,2,"health, healthcare"
16,person-swp/healthcare_SLM_1.0,2,"health, healthcare"
17,imbukwa/Tomato_Health_diseases,2,"disease, health"
18,drkumaranu165/healthcare-ner-colab,2,"health, healthcare"
19,sanjulamaduranga/BFL_Healthcare_covid_19,2,"health, healthcare"

Saved all 570 overlaps to overlapping_models.csv and overlapping_models.xlsx

In [11]:
from huggingface_hub import HfApi
import pandas as pd

!pip install XlsxWriter

with pd.ExcelWriter("health_models_clean.xlsx", engine='xlsxwriter') as writer:
    header_note = pd.DataFrame({
        "Note": ["This spreadsheet lists Hugging Face models related to health domains, including their download counts and associated tags."]
    })
    header_note.to_excel(writer, sheet_name="Health Models", index=False, startrow=0)
    combined_df.to_excel(writer, sheet_name="Health Models", index=False, startrow=3)


# Initialize API
api = HfApi()

# Define health-related search keywords
keywords = [
    "health", "medical", "clinical", "medicine", "disease",
    "treatment", "diagnosis", "healthcare", "hospital", "patient"
]

# Function to collect models for each keyword
def collect_models_from_search(api, query_str):
    df = pd.DataFrame(columns=['id', 'tags', 'downloads'])
    models = api.list_models(search=query_str)
    for model in models:
        # Skip models with missing fields
        if not model.id or not model.tags or model.downloads is None:
            continue
        new_row = {
            'id': model.id,
            'tags': model.tags,
            'downloads': model.downloads,
            'category': query_str
        }
        df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
    return df

# Collect and combine all models
all_dfs = [collect_models_from_search(api, kw) for kw in keywords]
combined_df = pd.concat(all_dfs, ignore_index=True)

# Remove duplicates
combined_df.drop_duplicates(subset='id', inplace=True)

# Save to Excel with a header note
with pd.ExcelWriter("health_models_clean.xlsx", engine='xlsxwriter') as writer:
    # Add header note
    header_note = pd.DataFrame({
        "Note": ["This spreadsheet lists Hugging Face models related to health domains, including their download counts and associated tags."]
    })
    header_note.to_excel(writer, sheet_name="Health Models", index=False, startrow=0)

    # Write model data below the header
    combined_df.to_excel(writer, sheet_name="Health Models", index=False, startrow=3)

print("Saved clean spreadsheet as 'health_models_clean.xlsx'")

Collecting XlsxWriter
  Downloading xlsxwriter-3.2.9-py3-none-any.whl.metadata (2.7 kB)
Downloading xlsxwriter-3.2.9-py3-none-any.whl (175 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.3/175.3 kB 4.2 MB/s eta 0:00:00
Installing collected packages: XlsxWriter
Successfully installed XlsxWriter-3.2.9
Saved clean spreadsheet as 'health_models_clean.xlsx'

In [14]:
with pd.ExcelWriter("health_models_clean.xlsx", engine='xlsxwriter') as writer:
    header_note = pd.DataFrame({
        "Note": ["This spreadsheet lists Hugging Face models related to health domains, including their download counts and associated tags."]
    })
    header_note.to_excel(writer, sheet_name="Health Models", index=False, startrow=0)
    combined_df.to_excel(writer, sheet_name="Health Models", index=False, startrow=3)

In [15]:
from huggingface_hub import HfApi
import pandas as pd

# Initialize API
api = HfApi()

# Health-related search keywords
keywords = [
    "health", "medical", "clinical", "medicine", "disease",
    "treatment", "diagnosis", "healthcare", "hospital", "patient"
]

# Function to collect models with parameters
def collect_models_with_parameters(api, query_str):
    df = pd.DataFrame(columns=['id', 'tags', 'downloads', 'parameters', 'category'])
    models = api.list_models(search=query_str)
    for model in models:
        # Skip if required fields are missing
        if not model.id or not model.tags or model.downloads is None:
            continue
        new_row = {
            'id': model.id,
            'tags': model.tags,
            'downloads': model.downloads,
            'parameters': getattr(model, 'model_parameters', None),  # May be None if not available
            'category': query_str
        }
        df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
    return df

# Collect and combine all models
all_dfs = [collect_models_with_parameters(api, kw) for kw in keywords]
combined_df = pd.concat(all_dfs, ignore_index=True)

# Remove duplicates
combined_df.drop_duplicates(subset='id', inplace=True)

# Save to Excel
with pd.ExcelWriter("health_models_with_parameters.xlsx", engine='xlsxwriter') as writer:
    # Header note
    header_note = pd.DataFrame({
        "Note": ["This spreadsheet lists Hugging Face models related to health domains, including their download counts, associated tags, and model parameters."]
    })
    header_note.to_excel(writer, sheet_name="Health Models", index=False, startrow=0)

    # Write model data
    combined_df.to_excel(writer, sheet_name="Health Models", index=False, startrow=3)

print("Saved spreadsheet as 'health_models_with_parameters.xlsx'")

Saved spreadsheet as 'health_models_with_parameters.xlsx'

In [ ]:
from huggingface_hub import HfApi
import pandas as pd

# Initialize Hugging Face API
api = HfApi()

# Define health-related keywords
keywords = [
    "health", "medical", "clinical", "medicine", "disease",
    "treatment", "diagnosis", "healthcare", "hospital", "patient"
]

# Function to collect models for each keyword
def collect_models(api, keyword):
    df = pd.DataFrame(columns=['id', 'tags', 'downloads', 'category'])
    models = api.list_models(search=keyword)
    for model in models:
        if not model.id or not model.tags or model.downloads is None:
            continue
        row = {
            'id': model.id,
            'tags': model.tags,
            'downloads': model.downloads,
            'category': keyword
        }
        df = pd.concat([df, pd.DataFrame([row])], ignore_index=True)
    return df

# Collect models across all keywords
all_dfs = [collect_models(api, kw) for kw in keywords]
combined_df = pd.concat(all_dfs, ignore_index=True)
combined_df.drop_duplicates(subset='id', inplace=True)

# One-hot encode tags efficiently
all_tags = sorted(set(tag for tags in combined_df['tags'] for tag in tags))
tag_matrix = pd.DataFrame([
    {tag: 1 if tag in tags else 0 for tag in all_tags}
    for tags in combined_df['tags']
])
tag_matrix.index = combined_df.index
combined_df = pd.concat([combined_df, tag_matrix], axis=1).copy()

# Save to Excel with header note
with pd.ExcelWriter("health_models_tag_matrix.xlsx", engine="xlsxwriter") as writer:
    header = pd.DataFrame({
        "Note": ["This spreadsheet lists Hugging Face models related to health domains, with binary tag indicators."]
    })
    header.to_excel(writer, sheet_name="Health Models", index=False, startrow=0)
    combined_df.to_excel(writer, sheet_name="Health Models", index=False, startrow=3)

print("✅ Saved spreadsheet as 'health_models_tag_matrix.xlsx'")

In [ ]:
import requests
from itertools import chain

# Step 1: Define health-related keywords
keywords = [
    "health", "medical", "clinical", "medicine", "disease",
    "treatment", "diagnosis", "healthcare", "hospital", "patient"
]

# Step 2: Collect models by keyword
def collect_models_from_search(api, query_str):
    df = pd.DataFrame(columns=['id', 'tags', 'downloads'])
    models = api.list_models(search=query_str)
    for model in models:
        if not model.id or not model.tags or model.downloads is None:
            continue
        new_row = {
            'id': model.id,
            'tags': model.tags,
            'downloads': model.downloads,
            'category': query_str
        }
        df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
    return df

# Step 3: Combine all keyword searches
all_dfs = [collect_models_from_search(api, kw) for kw in keywords]
combined_df = pd.concat(all_dfs, ignore_index=True).drop_duplicates(subset='id')

# Step 4: Normalize tags
def normalize_tag(tag):
    return tag.strip().lower().replace("-", "_")

combined_df['normalized_tags'] = combined_df['tags'].apply(lambda tags: [normalize_tag(tag) for tag in tags])

# Step 5: Fetch official Hugging Face tags
# Replace this with a real endpoint or static list if needed
reference_tags = {
    "text_classification", "token_classification", "translation", "summarization",
    "question_answering", "image_classification", "speech_recognition", "fill_mask",
    "text_generation", "ner", "medical", "clinical", "healthcare", "multilingual",
    "zero_shot_classification", "sentiment_analysis", "diagnosis", "disease"
}

# Step 6: Validate tags
def validate_tags(tag_list):
    return [tag in reference_tags for tag in tag_list]

combined_df['valid_tags'] = combined_df['normalized_tags'].apply(validate_tags)
combined_df['invalid_tag_count'] = combined_df['valid_tags'].apply(lambda x: x.count(False))

# Step 7: Save to Excel
with pd.ExcelWriter("health_models_clean.xlsx", engine='xlsxwriter') as writer:
    header_note = pd.DataFrame({
        "Note": ["This spreadsheet lists Hugging Face models related to health domains, including their download counts and associated tags."]
    })
    header_note.to_excel(writer, sheet_name="Health Models", index=False, startrow=0)
    combined_df.to_excel(writer, sheet_name="Health Models", index=False, startrow=3)

print("Saved clean spreadsheet with tag validation as 'health_models_clean.xlsx'")

In [ ]:
# Step 1: Flatten all tags and compute tag-level download totals
from collections import defaultdict

tag_downloads = defaultdict(int)
for _, row in combined_df.iterrows():
    for tag in row['tags']:
        tag_downloads[tag] += row['downloads']

# Step 2: Add tag downloads to each model row
def get_tag_downloads(tag_list):
    return [tag_downloads.get(tag, 0) for tag in tag_list]

combined_df['tag_downloads'] = combined_df['tags'].apply(get_tag_downloads)

# Step 3: Format tags and tag downloads as strings for Excel
combined_df['tags'] = combined_df['tags'].apply(lambda x: ", ".join(x))
combined_df['tag_downloads'] = combined_df['tag_downloads'].apply(lambda x: ", ".join(map(str, x)))

# Step 4: Select and reorder columns
final_df = combined_df[['id', 'tags', 'tag_downloads', 'downloads', 'category']]
final_df.columns = ['model id', 'tags', 'tag downloads', 'model downloads', 'category']

# Step 5: Save to Excel
with pd.ExcelWriter("health_models_clean.xlsx", engine='xlsxwriter') as writer:
    header_note = pd.DataFrame({
        "Note": ["This spreadsheet lists Hugging Face models related to health domains, including their download counts and associated tags."]
    })
    header_note.to_excel(writer, sheet_name="Health Models", index=False, startrow=0)
    final_df.to_excel(writer, sheet_name="Health Models", index=False, startrow=3)

print("Saved clean spreadsheet with tag-level downloads as 'health_models_clean.xlsx'")